title: "Deborah Udoh's Portfolio"
email: deborahudoh02@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # Leave empty if deploying to the root
url: "https://npdebs.github.io/my-portfolio/"
twitter_username: jekyllrb
github_username:  jekyll

collections:
  events:
    output: true
  talks:
    output: true


# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
