name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Ruby
        if: github.event.action != 'closed'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true

      - name: Install Jekyll and Bundler
        if: github.event.action != 'closed'
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll Site
        if: github.event.action != 'closed'
        run: bundle exec jekyll build --destination ./build

      - name: Deploy preview
        if: github.event.action != 'closed'
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Post deployment comment
        if: github.event.action != 'closed'
        uses: rossjrw/pr-preview-action@v1
        with:
          message: ":rocket: Preview deployed to [PR Preview](https://NPDebs.github.io/my-portfolio/pr-preview/pr-${{ github.event.number }}/)"
          GITHUB_TOKEN: ${{ secrets.PAT_GH_ACTION }}

      - name: Cleanup Preview
        if: github.event.action == 'closed'
        run: echo "Cleaning up preview for closed PR"